# -*- coding: utf-8 -*-
"""project_image_denoiser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16nLJaDJHDita175NR2_iJxZWR4Rnhogj

#### You'll build a denoising autoencoder:
#### → take clean MNIST digits
#### → SMASH them with noise
#### → train the model to clean them up
#### → watch damaged photos become perfect again!

##### 1. Load the data
"""

import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Download MNIST and turn each image into numbers between 0 and 1
to_numbers = transforms.ToTensor()

train_data = datasets.MNIST(root="./data", train=True,  download=True, transform=to_numbers)
test_data  = datasets.MNIST(root="./data", train=False, download=True, transform=to_numbers)

print("\ntraining pictures:", len(train_data))
print("test pictures:    ", len(test_data))

one_picture, one_label = train_data[0]
# print(one_picture)
print("\none picture shape:", one_picture.shape)
print("pixel range:", one_picture.min().item(), "to", one_picture.max().item())
print("its label is:", one_label, "  ← ⚠️ we will IGNORE this!")

"""##### 2. Add noise to the image"""

BATCH_SIZE = 128
NOISE_AMOUNT = 0.4

train_loader = DataLoader(train_data, batch_size = BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_data, batch_size = BATCH_SIZE, shuffle=True)

def add_noise(clean_pictures, amount=NOISE_AMOUNT):
  noise = torch.randn_like(clean_pictures) * amount # randn_like:- mostly between -2 to +2 centered around 0
  noisy_pictures = torch.clamp(clean_pictures + noise, 0.0, 1.0)
  return noisy_pictures

# Test it on 1 batch
clean_batch, _ = next(iter(train_loader))
noisy_batch = add_noise(clean_batch)

print("clean_batch shape:", clean_batch.shape)
print("noisy_batch shape:", noisy_batch.shape)
print()
print("clean pixel range:", round(clean_batch.min().item(), 3), "to", round(clean_batch.max().item(), 3))
print("noisy pixel range:", round(noisy_batch.min().item(), 3), "to", round(noisy_batch.max().item(), 3)) # Look at ONE pixel before and after
print("\none pixel: clean =", round(clean_batch[0, 0, 14, 14].item(), 3), "→ noisy =", round(noisy_batch[0, 0, 14, 14].item(), 3))

"""##### 3. See the damage"""

def show_pictures(rows_of_pictures, row_titles, how_many=8):
    fig, axes = plt.subplots(len(rows_of_pictures), how_many,
                             figsize=(how_many * 1.5, len(rows_of_pictures) * 1.7))
    for row_number, pictures in enumerate(rows_of_pictures):
        for col in range(how_many):
            ax = axes[row_number, col]
            ax.imshow(pictures[col].reshape(28, 28).cpu().detach(), cmap="gray")
            ax.axis("off")
            if col == 0:
                ax.set_title(row_titles[row_number], loc="left", fontsize=10)
    plt.tight_layout()
    plt.show()


show_pictures([clean_batch, noisy_batch], ["CLEAN", "NOISY"])

"""##### 4. Remove Noise (Autoencoder)"""

CODE_SIZE = 32

class Denoiser(nn.Module):
    def __init__(self, picture_size=784, code_size=CODE_SIZE):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Linear(picture_size, 256),   # 784 → 256   squeeze
            nn.ReLU(),
            nn.Linear(256, 64),             # 256 → 64    squeeze more
            nn.ReLU(),
            nn.Linear(64, code_size),       # 64  → 32    THE BOTTLENECK! 🗜️
        )

        self.decoder = nn.Sequential(
            nn.Linear(code_size, 64),       # 32  → 64    grow
            nn.ReLU(),
            nn.Linear(64, 256),             # 64  → 256   grow more
            nn.ReLU(),
            nn.Linear(256, picture_size),   # 256 → 784   full picture!
            nn.Sigmoid(),                   # squash to 0-1 ✅
        )

    def forward(self, x):
        flat    = x.view(x.size(0), -1)      # (B,1,28,28) → (B,784)
        code    = self.encoder(flat)
        rebuilt = self.decoder(code)
        return rebuilt, code


model = Denoiser().to(device)

rebuilt, code = model(noisy_batch.to(device))
print("input shape:  ", noisy_batch.shape)
print("code shape:   ", code.shape)
print("rebuilt shape:", rebuilt.shape)
print("\ntotal settings:", f"{sum(p.numel() for p in model.parameters()):,}")
print("squeeze:", 784 // CODE_SIZE, "times smaller 🗜️")

"""##### 5. Train and Test the model"""

LEARNING_RATE = 0.001
EPOCHS = 10

loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)


# ---------- STEP A: baselines — what do the numbers MEAN? ----------
clean_flat = clean_batch.view(clean_batch.size(0), -1)
noisy_flat = noisy_batch.view(noisy_batch.size(0), -1)

with torch.no_grad():
    untrained_out, _ = model(noisy_batch.to(device)) # Forward pass

print("BASELINES (smaller = better)")
print(f"  untrained model:          {loss_function(untrained_out.cpu(), clean_flat).item():.4f}")
print(f"  an all-black picture:     {loss_function(torch.zeros_like(clean_flat), clean_flat).item():.4f}")
print(f"  do nothing (keep noise):  {loss_function(noisy_flat, clean_flat).item():.4f}")
print()


# ---------- STEP B: a helper to measure honestly on unseen pictures ----------
def check_test_loss():
    model.eval()
    total, count = 0.0, 0
    with torch.no_grad():
        for clean, _ in test_loader:
            clean = clean.to(device)
            noisy = add_noise(clean)
            rebuilt, _ = model(noisy)
            target = clean.view(clean.size(0), -1)
            total += loss_function(rebuilt, target).item() * clean.size(0)
            count += clean.size(0)
    model.train()
    return total / count


# ---------- STEP C: the training loop ----------
train_history, test_history = [], []

for epoch in range(EPOCHS):
    model.train()
    running, seen = 0.0, 0

    for clean, _ in train_loader:                  # "_" = labels → thrown away 🗑️
        clean = clean.to(device)
        noisy = add_noise(clean)                   # ⭐ fresh damage EVERY batch

        optimizer.zero_grad()
        rebuilt, code = model(noisy)               # ⭐ feed the BROKEN picture
        target = clean.view(clean.size(0), -1)     # flatten the clean one to match
        loss = loss_function(rebuilt, target)      # ⭐ compare to the CLEAN picture
        loss.backward()
        optimizer.step()

        running += loss.item() * clean.size(0)
        seen += clean.size(0)

    train_loss = running / seen
    test_loss = check_test_loss()
    train_history.append(train_loss)
    test_history.append(test_loss)
    print(f"epoch {epoch+1:>2} | train {train_loss:.4f} | test {test_loss:.4f}")

print("\nTraining complete! 🎉")


# ---------- STEP D: draw the learning curve ----------
plt.figure(figsize=(7, 4))
plt.plot(range(1, EPOCHS + 1), train_history, marker="o", label="train")
plt.plot(range(1, EPOCHS + 1), test_history,  marker="o", label="test")
plt.axhline(y=loss_function(noisy_flat, clean_flat).item(), linestyle="--",
            color="gray", label="do nothing (noisy)")
plt.xlabel("epoch"); plt.ylabel("MSE loss"); plt.legend(); plt.title("Denoiser learning")
plt.show()

model.eval()

# Grab 128 test pictures the model has NEVER seen
clean_test, test_labels = next(iter(test_loader))
clean_test = clean_test.to(device)

torch.manual_seed(0)                       # same noise every time you run this
noisy_test = add_noise(clean_test)

with torch.no_grad():
    cleaned_test, _ = model(noisy_test)

# ---------- PART A: see it ----------
show_pictures([noisy_test, cleaned_test, clean_test],
              ["NOISY (input)", "CLEANED (model)", "ORIGINAL (target)"])

# ---------- PART B: measure each picture ----------
clean_flat = clean_test.view(clean_test.size(0), -1)
noisy_flat = noisy_test.view(noisy_test.size(0), -1)

print("pic | digit | noisy error | cleaned error | damage removed")
print("----+-------+-------------+---------------+---------------")
for i in range(8):
    noisy_err   = ((noisy_flat[i]   - clean_flat[i]) ** 2).mean().item()
    cleaned_err = ((cleaned_test[i] - clean_flat[i]) ** 2).mean().item()
    removed     = (noisy_err - cleaned_err) / noisy_err
    print(f" {i}  |   {test_labels[i].item()}   |   {noisy_err:.4f}    |"
          f"    {cleaned_err:.4f}     |     {removed:.0%}")

"""##### How our model groups output images"""

import numpy as np
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

model.eval()
all_codes, all_labels = [], []

with torch.no_grad():
    for clean, labels in test_loader:
        _, code = model(clean.to(device))      # only the ENCODER's output matters
        all_codes.append(code.cpu())
        all_labels.append(labels)

codes  = torch.cat(all_codes).numpy()          # stack every batch together
labels = torch.cat(all_labels).numpy()

print("codes shape: ", codes.shape)
print("labels shape:", labels.shape)
print("\none code (32 numbers):\n", codes[0].round(2))
print("its label:", labels[0])

def average_distance(group_a, group_b):
    differences = group_a[:, None, :] - group_b[None, :, :]   # every pair
    return np.linalg.norm(differences, axis=-1).mean()       # average length

sevens       = codes[labels == 7][:300]
other_sevens = codes[labels == 7][300:600]
nines        = codes[labels == 9][:300]
zeros        = codes[labels == 0][:300]

print("a 7 vs OTHER 7s:", round(average_distance(sevens, other_sevens), 2))
print("a 7 vs 9s:      ", round(average_distance(sevens, nines), 2))
print("a 7 vs 0s:      ", round(average_distance(sevens, zeros), 2))

"""##### PCA Map"""

def draw_map(points_2d, point_labels, title):
    plt.figure(figsize=(8, 7))
    dots = plt.scatter(points_2d[:, 0], points_2d[:, 1],
                       c=point_labels, cmap="tab10", s=3, alpha=0.6)
    for digit in range(10):
        centre = np.median(points_2d[point_labels == digit], axis=0)
        plt.text(centre[0], centre[1], str(digit), fontsize=16,
                 ha="center", va="center",
                 bbox=dict(boxstyle="circle", facecolor="white", alpha=0.85))
    plt.colorbar(dots, ticks=range(10), label="digit (the label we IGNORED)")
    plt.title(title)
    plt.show()


pca = PCA(n_components=2)
codes_2d_pca = pca.fit_transform(codes)

print("before:", codes.shape, "   after:", codes_2d_pca.shape)
print("spread kept by these 2 directions:", f"{pca.explained_variance_ratio_.sum():.0%}")

draw_map(codes_2d_pca, labels, "PCA: the best camera angle")

"""##### t-SNE Map"""

how_many = 3000      # t-SNE is slow, so we use a sample

tsne = TSNE(n_components=2, perplexity=30, random_state=0)
codes_2d_tsne = tsne.fit_transform(codes[:how_many])

print("before:", codes[:how_many].shape, "   after:", codes_2d_tsne.shape)

draw_map(codes_2d_tsne, labels[:how_many], "t-SNE: who sits next to whom")

"""##### Image search"""

query = 0                                         # the first test picture

distances = np.linalg.norm(codes - codes[query], axis=1)
nearest   = np.argsort(distances)[1:9]            # 8 closest, skipping itself

print("query picture is a:", labels[query])
print("its 8 nearest neighbours are:", labels[nearest])
print("their distances:", distances[nearest].round(2))

fig, axes = plt.subplots(1, 9, figsize=(13, 1.9))
for col, index in enumerate([query] + list(nearest)):
    axes[col].imshow(test_data[index][0].reshape(28, 28), cmap="gray")
    axes[col].set_title("QUERY" if col == 0 else f"#{col}", fontsize=9)
    axes[col].axis("off")
plt.tight_layout()
plt.show()

